"""empty message

Revision ID: 03a4874431bf
Revises: 197136ed6861
Create Date: 2024-03-23 10:14:23.701292

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '03a4874431bf'
down_revision = '197136ed6861'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('shopping_cart_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('price', sa.Integer(), nullable=False),
    sa.Column('shopping_cart_id', sa.Integer(), nullable=True),
    sa.Column('product_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.ForeignKeyConstraint(['shopping_cart_id'], ['shopping_carts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('shopping_carts', schema=None) as batch_op:
        batch_op.drop_constraint('shopping_carts_product_id_fkey', type_='foreignkey')
        batch_op.drop_column('price')
        batch_op.drop_column('quantity')
        batch_op.drop_column('product_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('shopping_carts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('product_id', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('quantity', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('price', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.create_foreign_key('shopping_carts_product_id_fkey', 'products', ['product_id'], ['id'])

    op.drop_table('shopping_cart_items')
    # ### end Alembic commands ###
