"""empty message

Revision ID: 23a3f20c480c
Revises: 03a4874431bf
Create Date: 2024-03-28 18:19:08.333928

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '23a3f20c480c'
down_revision = '03a4874431bf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_active', sa.Boolean(), nullable=False))
        batch_op.add_column(sa.Column('stripe_key', sa.String(length=120), nullable=False))
        batch_op.create_unique_constraint(None, ['stripe_key'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('stripe_key')
        batch_op.drop_column('is_active')

    # ### end Alembic commands ###
